### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [MaxShek/my_new_app#1]
This repository looks empty. Probably forgot to `git push origin master`?

**Comment by MaxShek** [comment]
Professor Frtiz,

I went home yesterday and I just got back to East Lansing. I’m unsure if you still have free time this afternoon but if you did I would be free to meet to help me finish.

When I push to github I get the following error:

ssh: connect to host github.com port 22: Operation timed out
fatal: Could not read from remote repository.

Looking into it. I will fix the other assignment as well.

Thanks,

Maxwell Shek

**Comment by chrisvfritz** [comment]
Sorry, I'm not able to meet today. `Operation timed out` suggests a possible Internet connection issue. Are you sure you were connected to the Internet when you tried this?

**Comment by MaxShek** [comment]
Shouldn't be empty any more, also just realized my replies to e-mails come in as comments. Whoops.

**Comment by chrisvfritz** [comment]
I see some four-space tabs I'd like you to [update to two-space tabs here](https://github.com/MaxShek/my_new_app/blob/master/app/assets/stylesheets/static.css#L2-L4). The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have *every* file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Then there's also a criterion of this project it doesn't look like you've completed yet:

> have at least 1 helper method that is used for some visible effect on at least 1 page

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by chrisvfritz** [comment]
:+1: Looks much better!
